services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks: [test-network]
    volumes:
      - rabbitmq_data_test:/var/lib/rabbitmq


  posts_Test_db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: posts_Test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - posts_Test_db_data:/var/lib/postgresql/data
    networks: [test-network]

  auth_Test_db:
    image: postgres:15.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: auth_Test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - auth_Test_db_data:/var/lib/postgresql/data
    networks: [test-network]

  subscribe_Test_db:
    image: postgres:15.3
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: subscribe_Test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - subscribe_Test_db_data:/var/lib/postgresql/data
    networks: [test-network]

  admin_Test_db:
    image: postgres:15.3
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: admin_Test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - admin_Test_db_data:/var/lib/postgresql/data
    networks: [test-network]

  posts_service:
    build:
      context: ./posts_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./posts_service/.env.test
    volumes:
      - ./posts_service:/app
    depends_on:
      - posts_Test_db
      - rabbitmq
    networks: [test-network]

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./auth_service/.env.test
    volumes:
      - ./auth_service:/app
    depends_on:
      - auth_Test_db
      - rabbitmq
    networks: [test-network]

  subscription_service:
    build:
      context: ./subscription_service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    env_file:
       - ./subscription_service/.env.test
    volumes:
      - ./subscription_service:/app
    depends_on:
      - subscribe_Test_db
      - rabbitmq
    networks: [test-network]

  admin_service:
    build:
      context: ./admin_service
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
    env_file:
      - ./admin_service/.env.test
    volumes:
      - ./admin_service:/app
    depends_on:
      - admin_Test_db
      - rabbitmq
    networks: [test-network]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth_service
      - admin_service
      - posts_service
      - subscription_service
    networks: [test-network]

volumes:
  posts_Test_db_data:
  auth_Test_db_data:
  subscribe_Test_db_data:
  admin_Test_db_data:
  rabbitmq_data_test:

networks:
  test-network:
    driver: bridge
