"""remove verification_code from users

Revision ID: 8d682b4ef273
Revises: 786527123c15
Create Date: 2025-05-05 10:23:21.301660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d682b4ef273'
down_revision: Union[str, None] = '786527123c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
